# Generated by Django 4.0.6 on 2022-07-20 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entity1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attr1', models.IntegerField()),
                ('attr2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='entity2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attr1', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='relation1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr1', models.IntegerField()),
                ('id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor1.entity1')),
                ('id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor1.entity2')),
            ],
        ),
    ]
