# Generated by Django 4.0.6 on 2022-08-15 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('published_year', models.IntegerField()),
                ('poster_dir', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor1.movie')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='relation1',
            name='id1',
        ),
        migrations.RemoveField(
            model_name='relation1',
            name='id2',
        ),
        migrations.DeleteModel(
            name='entity1',
        ),
        migrations.DeleteModel(
            name='entity2',
        ),
        migrations.DeleteModel(
            name='relation1',
        ),
        migrations.AddField(
            model_name='rating',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor1.user'),
        ),
    ]
